project:
  type: website
  output-dir: /Users/juanpazmino/Documents/Desarrollo/Personal_projects/SpotifyDataVis/docs

website:
  title: "Spotify Data Analytics"
  navbar:
    background: "#1DB954"
    left:
      - href: index.qmd
        text: "Inicio"
      - href: music_evolution.qmd
        text: "Evolución Musical"

format:
  html:
    page-layout: full
    theme: darkly
    toc: true