project:
  type: website
  output-dir: /Users/juanpazmino/Documents/Desarrollo/Personal_projects/SpotifyDataVis/docs

website:
  title: "Historial de Spotify"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme: cosmo
    toc: true

code-fold: true

execute:
  freeze: auto