project:
  type: website
  output-dir: /Users/juanpazmino/Documents/Desarrollo/Personal_projects/SpotifyDataVis/docs

website:
  title: "Spotify Data Analytics"
  navbar:
    background: "#1DB954"
    left:
      - href: index.qmd
        text: "Generos"
      - href: music_evolution.qmd
        text: "Evolución Musical"
      - href: popularity_bias.qmd
        text: "Sesgo de popularidad"
      - href: music_attributes.qmd
        text: "Atributos musicales"
      - href: procesamiento.qmd
        text: "Procesamiento"

format:
  html:
    page-layout: full
    theme: darkly
    toc: true